apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.image.secret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $val := .Values.env.global }}{{ if $val }}
            - name: {{ $key  }}
              value: {{ $val | quote }}
            {{ end }}{{- end }}
            {{- if .Values.env.local.DB_HOST }}
            - name: DB_HOST
              value: "{{ .Values.env.local.DB_HOST }}"
            {{- else }}
            - name: DB_HOST
              value: "{{ .Release.Name }}-postgresql:5432"
            {{- end }}
            {{- if .Values.env.local.CH_SOLUTIONS_KUBE_API_URL }}
            - name: CH_SOLUTIONS_KUBE_API_URL
              value: "{{ .Values.env.local.CH_SOLUTIONS_KUBE_API_URL }}"
            {{- else }}
            - name: CH_SOLUTIONS_KUBE_API_URL
              value: "{{ .Release.Name }}-kube:1214"
            {{- end }}
            {{- if .Values.env.local.CH_SOLUTIONS_RESOURCE_URL }}
            - name: CH_SOLUTIONS_RESOURCE_URL
              value: "{{ .Values.env.local.CH_SOLUTIONS_RESOURCE_URL }}"
            {{- else }}
            - name: CH_SOLUTIONS_RESOURCE_URL
              value: "{{ .Release.Name }}-resource:1213"
            {{- end }}
            {{- if .Values.env.local.DB_PASSWORD }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: pg-password
            {{- else if .Values.tags.platformdb }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgres-password
            {{- end }}
