tags:
  db: true
  platformdb: false

replicaCount: 1

image:
  repository: containerum/solutions
  tag: v1.0.0
  pullPolicy: IfNotPresent
  secret:

service:
  port: 6767
  targetPort: 6767
  externalIP:

env:
  global:
    CH_SOLUTIONS_DEBUG: "false"
    CH_SOLUTIONS_TEXTLOG: "false"
    CH_SOLUTIONS_PORT: ":6767"
    CH_SOLUTIONS_DB: "postgres"
    DB_BASE: "solutions"
    DB_USER: "solutions"
    DB_SSLMODE: "false"
  local:
    DB_HOST: "postgres-master.postgres.svc.cluster.local:5432"
    CH_SOLUTIONS_KUBE_API_URL: "http://kube-api:1214"
    CH_SOLUTIONS_RESOURCE_URL: "http://resource-service:1213"
    DB_PASSWORD:

postgresql:
  persistence:
    enabled: false
  postgresDatabase: permissions
  # postgresUser: postgres
  # postgresPassword: password
