tags:
  db: true
  platformdb: false

replicaCount: 1

image:
  repository: containerum/solutions
  tag: v1.0.0
  pullPolicy: IfNotPresent
  secret:

service:
  port: 6767
  targetPort: 6767
  externalIP:

env:
  global:
    CH_SOLUTIONS_DEBUG: "false"
    CH_SOLUTIONS_TEXTLOG: "false"
    CH_SOLUTIONS_DB: "postgres"
    CH_SOLUTIONS_PG_LOGIN: "solutions"
    CH_SOLUTIONS_PG_DBNAME: "solutions"
    CH_SOLUTIONS_PG_NOSSL: "true"
  local:
    CH_SOLUTIONS_PG_ADDR: "postgres-master.postgres.svc:5432"
    CH_SOLUTIONS_KUBE_API_URL: "http://kube:1214"
    CH_SOLUTIONS_RESOURCE_URL: "http://resource:1213"
    CH_SOLUTIONS_PG_PASSWORD:

postgresql:
  persistence:
    enabled: false
  postgresDatabase: permissions
  # postgresUser: postgres
  # postgresPassword: password
