tags:
  db: true
  platformdb: false

replicaCount: 1

image:
  repository: containerum/solutions
  tag: v1.0.0
  pullPolicy: IfNotPresent
  secret:

service:
  port: 6767
  targetPort: 6767
  externalIP:

env:
  global:
    DEBUG: "false"
    TEXTLOG: "false"
    DB: "postgres"
    PG_LOGIN: "solutions"
    PG_DBNAME: "solutions"
    PG_NOSSL: "true"
  local:
    PG_ADDR: "postgres-master.postgres.svc.cluster.local:5432"
    KUBE_API_URL: "http://kube-api:1214"
    RESOURCE_URL: "http://resource-service:1213"
    PG_PASSWORD:

postgresql:
  persistence:
    enabled: false
  postgresDatabase: permissions
  # postgresUser: postgres
  # postgresPassword: password
